FROM python:3.10.9

WORKDIR /src

COPY ./requirements.txt /src/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /src/requirements.txt

COPY ./app /src/app
COPY ./models /src/models

EXPOSE 8000

CMD ["uvicorn", "app.model_api:app", "--host", "0.0.0.0", "--port", "8000"]